TITULO_JANELA = "Jogo de Damas"
TITULO_MENU = "Damas Portuguesas - Menu"

TAMANHO_TABULEIRO = 8
TAMANHO_CASA = 60
RAIO_PECA = 25

COR_CASA_CLARA = "#F0D9B5"
COR_CASA_ESCURA = "#B58863"
COR_BORDA = "#000000"

COR_PECA_BRANCA = "#BAB6B6"
COR_BORDA_PECA_BRANCA = "#F5E8E8"
COR_PECA_PRETA = "#222222"
COR_BORDA_PECA_PRETA = "#000000"

COR_SELECAO = "#FFFF00"
COR_DESTINO_POSSIVEL = "#90EE90"
COR_BORDA_DESTINO_POSSIVEL = "#006400"

JOGADOR_BRANCO = "branco"
JOGADOR_PRETO = "preto"

LINHAS_INICIAIS_PRETO = range(0, 3)
LINHAS_INICIAIS_BRANCO = range(5, 8)
